<div class="default_space">
    <div class="default_header2"><a href="chat.php" title="Le Chat vous permet de discuter en temps r&eacute;el avec les autres joueurs connect&eacute;s">Piloris</a></div>
    <div class="default_header2"><a href="chat.php" title="Le Chat vous permet de discuter en temps r&eacute;el avec les autres joueurs connect&eacute;s"><font color="#DB5656">Règle</font></a></div>
    <div class="default_header2"><a href="chat.php" title="Le Chat vous permet de discuter en temps r&eacute;el avec les autres joueurs connect&eacute;s"><font color="#DB5656">Chat</font></a></div>
    <div class="default_header2"><a href="http://www.spaceswars.com/forum/viewtopic.php?f=321&t=11381" target="_blank" title="Le guide officiel pour apprendre &agrave; jouer sur SpacesWars">Aide / Guide</a></div>
    <div class="default_header2"><a href="http://spaceswars.com/forum/" target="_blank"  title="Le forum est un espace permettant &agrave; chacun de s'exprimer sur un sujet, de montrer ses plus beaux combats, de proposer une id&eacute;e pouvant am&eacute;liorer le jeu ou tout simplement de faire connaissance avec d'autres personnes">Forum</a></div>
    <div class="default_header2"><a href="options.php" title="Les Options vous permettent de faire des modifications sur votre compte, comme changer le mot de passe, l'adresse mail, le nombre de sondes envoy&eacute;es mais aussi de regarder les statistiques de son compte (nombre de raids effectu&eacute;s, pertes caus&eacute;es, subies etc...)">Options</a></div>
    <div class="default_header2"><a href="support.php" title="Le Support vous permet de prendre contact avec l'administrateur du jeu, si vous avez des questions ou des probl&egrave;mes c'est le meilleur endroit pour obtenir une r&eacute;ponse rapide"> Support</a></div>
</div>
<br>